### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by baitun** [rudensergey/darkroom#17]
Fix all errors, reported by W3C validator here:
http://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Frudensergey.github.io%2Fdarkroom%2F#l118c59

**Comment by rudensergey** [comment]
Done @baitun

**Comment by baitun** [comment]
> Done @baitun

"Done" - is when you send a PR.
