### ISSUE TITLE
Learn git

### ISSUE THREAD

**Issue by baitun** [rudensergey/darkroom#2]
- [x] Learn full course on https://learngitbranching.js.org/
- [x] Learn how to create new branch with git from console and from VSCode
- [x] Learn how to make Pull Request (PR) on github

Deadline: 2019-05-16

**Comment by rudensergey** [comment]
<img width="640" alt="Screenshot 2019-05-16 at 04 20 12" src="https://user-images.githubusercontent.com/44585564/57819619-fcfe5380-7791-11e9-8ed1-ed53ce83a6b1.png">

**Comment by rudensergey** [comment]
git commit - create new commit
git brunch "name" - create new branch
git checkout ''name" - switch to this brunch

git merge "name" - merging two branches
git rebase "name" - make a linear commits
git checkout HEAD^ - level up to the commit
git checkout ^~123 - step up with number of steps
git branch -f "required commit" "destination" - move commit or branch to the current place

git reset HEAD~ - reset our commits inch steps back
git revert HEAD
git cherry-pick "hash commits" - attach commits to the master branch
git rebase HEAD~"number" - rebase number of commits with interactive window
git tag v1 c1 - tag like an anchor

git clone - copy your commit steps to remote place
git fetch - download you commit data to local storage
git pull - analog fetch


How to create new branch from command line
$ git checkout -b [name_of_your_new_branch]
$ git push origin [name_of_your_new_branch]

$ git remote add [name_of_your_remote] [name_of_your_new_branch]
$ git push [name_of_your_new_remote] [url]
$ git fetch [name_of_your_remote]
$ git merge [name_of_your_remote]/develop
$ git branch -d [name_of_your_new_branch]

**Comment by baitun** [comment]
Ok, I think this task has been done, so I close it up.
