### ISSUE TITLE
Add header

### ISSUE THREAD

**Issue by baitun** [rudensergey/darkroom#3]
You need to make html and css for header element, so it's looks like
![image](https://user-images.githubusercontent.com/5827605/57656419-f4b2e680-75e0-11e9-89af-3896267d6aa6.png)
There should be:

- [x] Logo
- [x] Site name
- [x] Buttons: explore, cart, login, create a gallery

For this task you need to create branch called `task-3`, commit all changes to this branch, do `git push` and create a `Pull Request`.

**Deadline: 2019-05-19**

**Comment by baitun** [comment]
You can use css `grid` or `flexbox`.
You are not allowed to use `float` and `table`

**Comment by baitun** [comment]
For buttons (that's actually are links) you need to use '<a>....</a>' tag.

**Comment by baitun** [comment]
@rudensergey I remind you that the deadline soon

**Comment by rudensergey** [comment]
wait for new tasks!)

**Comment by rudensergey** [comment]
I haven't done only hover for 2 buttons I thought ill handle with this later

**Comment by baitun** [comment]
You need to create Pull Request, so I can check it
Go to [Pull Requests](https://github.com/rudensergey/darkroom/pulls) tab, click `New pull request` and select branches:  
base: **master**  
compare: **task-3**

**Comment by rudensergey** [comment]
Done

**Comment by baitun** [comment]
Done in #5 
Everything is OK
🎉🎉🎉 Congrats! 👏👏👏
