### ISSUE TITLE
Add slider under header

### ISSUE THREAD

**Issue by rudensergey** [rudensergey/darkroom#4]
- [x] Create new branch

- [ ] Add picture

- [ ] Set all buttons and effects

- [ ] Make this shit adaptive (unnecessary)

Don't use float and other old technology

**Comment by rudensergey** [comment]
I don't know how to fix header to the top. Position: fixed doesn't work 
code here https://github.com/rudensergey/darkroom/commit/f045e2ddc43180db348206d40c239cfe788280d7

**Comment by rudensergey** [comment]
add commit from the third task not on purpose, just forgot about git checkout

**Comment by rudensergey** [comment]
I've decided to create underline effect

**Comment by baitun** [comment]
@rudensergey, how is it going?
If task is done, create new Pull Request, so I can review it.

**Comment by baitun** [comment]
ping @rudensergey
